# roles/bind_install/tasks/main.yml
---

# Initialise distribution-specific variables
- name: Pull facts
  action: setup

- include_vars: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"
  tags: httpd

- include_vars: "Debian.yml"
  when:
    - ansible_os_family == "Debian"
  tags: httpd

- name: Check whether `bind_zone_master_server_ip` was set
  assert:
    that: bind_zone_master_server_ip is defined

- name: install BIND 
  yum: name=bind state=present

- name: Creates directory
  file: 
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ named_group }}"
    mode: 0770
  with_items:
    - "{{ bind_dir }}"
    - "/etc/named"
    - "/etc/named/zones"
  tags: bind

- name: Ensure runtime directories referenced in config exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ named_group }}"
    mode: 0770
  with_items:
    - "{{ bind_dir }}"
    - "/etc/named"
    - "/etc/named/zones"
  tags: bind

- name: Create serial
  command: date +%y%m%d%H
  register: timestamp
  changed_when: false
  tags: bind

- include: master.yml

- name: Start BIND service
  service:
    name: "{{ bind_service }}"
    state: started
    enabled: yes
  tags: bind
